---
include:
  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TB Slot2_TB Slot3_TB
  #   artifact-name: MRM_TB_TB_TB

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_ENC Slot2_ENC Slot3_ENC
  #   artifact-name: MRM_ENC_ENC_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_JOY Slot2_JOY Slot3_JOY
  #   artifact-name: MRM_JOY_JOY_JOY

  - board: seeeduino_xiao_ble
    shield: MRM rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TB Slot2_TPD Slot3_ENC
    artifact-name: MRM_TB_TPD_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_ENC Slot2_JOY Slot3_TB
  #   artifact-name: MRM_ENC_JOY_TB

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_ENC Slot2_TB Slot3_JOY
  #   artifact-name: MRM_ENC_TB_JOY

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_JOY Slot2_ENC Slot3_TB
  #   artifact-name: MRM_JOY_ENC_TB

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_JOY Slot2_TB Slot3_ENC
  #   artifact-name: MRM_JOY_TB_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_RZT Slot2_ENC Slot3_JOY
  #   artifact-name: MRM_RZT_ENC_JOY

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_RZT Slot2_ENC Slot3_TB
  #   artifact-name: MRM_RZT_ENC_TB

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_RZT Slot2_JOY Slot3_ENC
  #   artifact-name: MRM_RZT_JOY_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_RZT Slot2_JOY Slot3_TB
  #   artifact-name: MRM_RZT_JOY_TB

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_RZT Slot2_TB Slot3_ENC
  #   artifact-name: MRM_RZT_TB_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_RZT Slot2_TB Slot3_JOY
  #   artifact-name: MRM_RZT_TB_JOY

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TB Slot2_ENC Slot3_JOY
  #   artifact-name: MRM_TB_ENC_JOY

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TB Slot2_JOY Slot3_ENC
  #   artifact-name: MRM_TB_JOY_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TPD Slot2_ENC Slot3_JOY
  #   artifact-name: MRM_TPD_ENC_JOY

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TPD Slot2_ENC Slot3_TB
  #   artifact-name: MRM_TPD_ENC_TB

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TPD Slot2_JOY Slot3_ENC
  #   artifact-name: MRM_TPD_JOY_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TPD Slot2_JOY Slot3_TB
  #   artifact-name: MRM_TPD_JOY_TB

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TPD Slot2_TB Slot3_ENC
  #   artifact-name: MRM_TPD_TB_ENC

  # - board: seeeduino_xiao_ble
  #   shield: MRM rgbled_adapter
  #   snippet: zmk-usb-logging studio-rpc-usb-uart Slot1_TPD Slot2_TB Slot3_JOY
  #   artifact-name: MRM_TPD_TB_JOY

  - board: seeeduino_xiao_ble
    shield: settings_reset
